name: Dependabot

on:
  push:
    branches: [ dependabot/npm_and_yarn/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Autofix lockfile
        run: |
          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock

          # if package.json was not updated, upgrade the dependency
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up `git log -1 --pretty=%s | awk '{ print $2 }'`

          # restore package.json from the last commit
          git checkout HEAD -- package.json

          yarn install

          yarn deduplicate

          git add yarn.lock

      - name: Config Git
        run: |
          # use personal access token to allow triggering new workflow
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.GH_TOKEN }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"

      - name: Check for changes
        id: changes
        run: |
          git update-index --refresh || true
          echo "::set-output name=changes::$(git diff-index HEAD)"

      - name: Commit changes
        if: steps.changes.outputs.changes # If there are changes, continue
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email '49699333+dependabot[bot]@users.noreply.github.com'
          git commit --amend --no-edit
          git push -f
